### ISSUE TITLE
NVIDIA Jetson  using pynini

### ISSUE THREAD

**Issue by Isshang** [conda-forge/pynini-feedstock#23]
### Comment:

I want to use pynini on my Jetson orin nano platform, which is a Linux platform with aarch64 architecture. Is there any way to install it?

**Comment by kylebgorman** [comment]
Hi @Isshang,This is the wrong place for this question, since this repo is code to maintain Conda-Forge’s compilation of Pynini, and Conda-Forge (and Conda in general) don’t support ARM (except for the new MacOS processors). This is not the repo for Pynini itself.That said, yes, it should be possible to compile Pynini on any POSIX platform with enough C99 and C++17 support. You’ll have to compile it yourself.You’ll first want to compile OpenFst 1.8.2 locally (configure with enable-grm) and then build and install Pynini 2.1.5 like you would for any Python package. If you have trouble with the post1 releases try the earlier ones.The one limitation is: the compilation process, particularly for OpenFst, requires a decent amount of compute and memory and it’s been known to crash with an OOM (or swap forever) on embedded systems.I’ll close this when I am back at a desktop.On Nov 24, 2023, at 7:15 AM, Isshang ***@***.***> wrote:﻿
Comment:
I want to use pynini on my Jetson orin nano platform, which is a Linux platform with aarch64 architecture. Is there any way to install it?
